\f C:\#Git\ReadSQL\ex;
\cs test4.dbx;

\# "Example from SPSS Modeler node Distinct PARTNER order by SPOTREBA_MWH_AKTUALNI_EE desc, include all but first.", tc= 2;

SELECT T0.PARTNER AS PARTNER,T0.DISTRIBUTOR AS DISTRIBUTOR,T0."SPOTREBA_MWH_AKTUALNI_EE" AS "SPOTREBA_MWH_AKTUALNI_EE" FROM
(SELECT T0.PARTNER AS PARTNER,T0.DISTRIBUTOR AS DISTRIBUTOR,T0."SPOTREBA_MWH_AKTUALNI_EE" AS "SPOTREBA_MWH_AKTUALNI_EE",T0."ROW_NUMBER" AS "ROW_NUMBER" FROM
(SELECT T0.PARTNER AS PARTNER,T0.DISTRIBUTOR AS DISTRIBUTOR,T0."SPOTREBA_MWH_AKTUALNI_EE" AS "SPOTREBA_MWH_AKTUALNI_EE",
ROW_NUMBER() OVER ( PARTITION BY T0.PARTNER ORDER BY T0."SPOTREBA_MWH_AKTUALNI_EE" DESC) AS "ROW_NUMBER" FROM "Moje_TEMP" T0) T0
WHERE (T0."ROW_NUMBER" <> 1)) T0;
