\f C:\#Git\ReadSQL\ex;
\cs test4.dbx;

\# "Example from SPSS Modeler node Aggregate PARTNER with various functions.", tc= 2;

SELECT T0.PARTNER AS PARTNER,MIN(T0.DISTRIBUTOR) AS "DISTRIBUTOR_Min",MAX(T0.DISTRIBUTOR) AS "DISTRIBUTOR_Max",
COUNT(T0.DISTRIBUTOR) AS "DISTRIBUTOR_Count",SUM(T0."SPOTREBA_MWH_AKTUALNI_EE") AS "SPOTREBA_MWH_AKTUALNI_EE_Sum",
AVG(T0."SPOTREBA_MWH_AKTUALNI_EE") AS "SPOTREBA_MWH_AKTUALNI_EE_Mean",MIN(T0."SPOTREBA_MWH_AKTUALNI_EE") AS "SPOTREBA_MWH_AKTUALNI_EE_Min",
MAX(T0."SPOTREBA_MWH_AKTUALNI_EE") AS "SPOTREBA_MWH_AKTUALNI_EE_Max",
(CASE WHEN COUNT(T0."SPOTREBA_MWH_AKTUALNI_EE") > 1 THEN AVG("SPOTREBA_MWH_AKTUALNI_EE"*"SPOTREBA_MWH_AKTUALNI_EE") - AVG("SPOTREBA_MWH_AKTUALNI_EE")*AVG("SPOTREBA_MWH_AKTUALNI_EE") ELSE NULL END) AS "SPOTREBA_MWH_AKTUALNI_EE_SDev",
COUNT(T0."SPOTREBA_MWH_AKTUALNI_EE") AS "SPOTREBA_MWH_AKTUALNI_EE_Count",
COUNT(*) AS "Record_Count" FROM "Moje_TEMP" T0 GROUP BY T0.PARTNER;

\# variance (CASE WHEN COUNT(T0."SPOTREBA_MWH_AKTUALNI_EE") > 1 THEN "SPOTREBA_MWH_AKTUALNI_EE_SDev"*"SPOTREBA_MWH_AKTUALNI_EE_SDev" ELSE NULL END) AS "SPOTREBA_MWH_AKTUALNI_EE_Variance",;
