\f C:\#Git\ReadSQL\ex;
\cs test4.dbx;

\# "Example from SPSS Modeler node Select discard.", tc= 2;

SELECT T0.PARTNER AS PARTNER,T0.EINZDAT AS EINZDAT,T0.DIVISION AS DIVISION,T0.DISTRIBUTOR AS DISTRIBUTOR,
T0."SPOTREBA_MWH_AKTUALNI_EE" AS "SPOTREBA_MWH_AKTUALNI_EE" FROM "Moje_TEMP" T0
WHERE NOT(((T0."SPOTREBA_MWH_AKTUALNI_EE" IS NULL) OR (T0.EINZDAT >= '2022-01-01 00:00:00')));
