\f C:\#Git\ReadSQL\ex;
\cms Test;

\# "Example from SPSS Modeler node Select, Append.", tc= 2;

SELECT T0.PARTNER AS PARTNER,T0.EINZDAT AS EINZDAT,T0.DIVISION AS DIVISION,T0.DISTRIBUTOR AS DISTRIBUTOR,
T0."SPOTREBA_MWH_AKTUALNI_EE" AS "SPOTREBA_MWH_AKTUALNI_EE",T0."Input" AS "Input" FROM
(SELECT T0.PARTNER AS PARTNER,T0.EINZDAT AS EINZDAT,T0.DIVISION AS DIVISION,T0.DISTRIBUTOR AS DISTRIBUTOR,
   T0."SPOTREBA_MWH_AKTUALNI_EE" AS "SPOTREBA_MWH_AKTUALNI_EE",N'1' AS "Input",N'0' AS APPENDXYZ
    FROM "Moje_TEMP" T0 WHERE NOT(((T0."SPOTREBA_MWH_AKTUALNI_EE" IS NULL) OR (T0.EINZDAT >= CONVERT(DATETIME, N'2022-01-01 00:00:00', 120))))
     UNION ALL
SELECT T0.PARTNER AS PARTNER,T0.EINZDAT AS EINZDAT,T0.DIVISION AS DIVISION,T0.DISTRIBUTOR AS DISTRIBUTOR,
   T0."SPOTREBA_MWH_AKTUALNI_EE" AS "SPOTREBA_MWH_AKTUALNI_EE",N'2' AS "Input",N'1' AS APPENDXYZ
    FROM "Moje_TEMP" T0 WHERE ((T0."SPOTREBA_MWH_AKTUALNI_EE" IS NULL) OR (T0.EINZDAT >= CONVERT(DATETIME, N'2022-01-01 00:00:00', 120)))) T0;
