\f C:\#Git\ReadSQL\ex;
\cs test4.dbx;

\# "Example from SPSS Modeler node Select, Append.", tc= 2;

SELECT T0.PARTNER AS PARTNER,T0.EINZDAT AS EINZDAT,T0.DIVISION AS DIVISION,T0.DISTRIBUTOR AS DISTRIBUTOR,
T0."SPOTREBA_MWH_AKTUALNI_EE" AS "SPOTREBA_MWH_AKTUALNI_EE",T0."Input" AS "Input" FROM
(SELECT T0.PARTNER AS PARTNER,T0.EINZDAT AS EINZDAT,T0.DIVISION AS DIVISION,T0.DISTRIBUTOR AS DISTRIBUTOR,
   T0."SPOTREBA_MWH_AKTUALNI_EE" AS "SPOTREBA_MWH_AKTUALNI_EE", '1' AS "Input", '0' AS APPENDXYZ
    FROM "Moje_TEMP" T0 WHERE NOT(((T0."SPOTREBA_MWH_AKTUALNI_EE" IS NULL) OR (T0.EINZDAT >= '2022-01-01 00:00:00')))
     UNION ALL
SELECT T0.PARTNER AS PARTNER,T0.EINZDAT AS EINZDAT,T0.DIVISION AS DIVISION,T0.DISTRIBUTOR AS DISTRIBUTOR,
   T0."SPOTREBA_MWH_AKTUALNI_EE" AS "SPOTREBA_MWH_AKTUALNI_EE", '2' AS "Input", '1' AS APPENDXYZ
    FROM "Moje_TEMP" T0 WHERE ((T0."SPOTREBA_MWH_AKTUALNI_EE" IS NULL) OR (T0.EINZDAT >= '2022-01-01 00:00:00'))) T0;
