\cms gdpr;

CREATE TABLE "##CLEMTMP7649E00E1" ( "C_GDPR_DS" BIGINT,CHANNEL VARCHAR(8),"CHANNEL_CRM" VARCHAR(1),PU NVARCHAR(5),RSN BIGINT,"DATE" DATETIME,TXTMD VARCHAR(40));



INSERT INTO "##CLEMTMP7649E00E1" ("C_GDPR_DS",CHANNEL,"CHANNEL_CRM",PU,RSN,"DATE",TXTMD) SELECT T0."C_GDPR_DS" AS "C_GDPR_DS",T0.CHANNEL AS CHANNEL,T0."CHANNEL_CRM" AS "CHANNEL_CRM",T0.PU AS PU,T0.RSN AS RSN,T0."DATE" AS "DATE",T0.TXTMD AS TXTMD FROM (SELECT T0."C_GDPR_DS" AS "C_GDPR_DS",T0.CHANNEL AS CHANNEL,T0."CHANNEL_CRM" AS "CHANNEL_CRM",T0.PU AS PU,T0.RSN AS RSN,T0."DATE" AS "DATE",T0.TXTMD AS TXTMD,T0."ROW_NUMBER" AS "ROW_NUMBER" FROM (SELECT T0."GDPR_ID" AS "C_GDPR_DS",T0.CHANNEL AS CHANNEL,T0."CHANNEL_CRM" AS "CHANNEL_CRM",T0.PU AS PU,T0.RSN AS RSN,T0."DATE" AS "DATE",T0.TXTMD AS TXTMD,ROW_NUMBER() OVER ( PARTITION BY T0."GDPR_ID" ORDER BY T0."DATE" DESC) AS "ROW_NUMBER" FROM "dbo".GDPR T0 WHERE (((T0.PU = N'ZPU20') AND (T0."CHANNEL_CRM" = N'T')) AND (T0."DATE" >= CONVERT(DATETIME, CAST(GETDATE() AS DATE), 120)))) T0 WHERE (T0."ROW_NUMBER" = 1)) T0;



SELECT T0."C_GDPR_DS" AS "C_GDPR_DS",T0.CHANNEL AS CHANNEL,T0."CHANNEL_CRM" AS "CHANNEL_CRM",T0.PU AS PU,T0.RSN AS RSN,T0."DATE" AS "DATE",T0.TXTMD AS TXTMD,N'ANO' AS "GDPR_OK" FROM "##CLEMTMP7649E00E1" T0;
