\f fill;

\r aaa.txtx l = 0;

\df n = {['GENDER_TXT','TITLE_ACA1T']: "#Chybí", 'VEK': 0, ['ZZDEATHDT' 'BPCONTFCT_ORG']: 0,
['LEGAL_ENTYT' 'ZAMESTNANEC']: ["#A" "#B"], ['SPOTREBA_MWH_AKTUALNI_PLYN', 'SPOTREBA_MWH_AKTUALNI_EE'] : [-1,-2] };

\q;

\df n = ['GENDER_TXT': 0,'TITLE_ACA1T': "#Chybí", 'VEK': 0, 'ZZDEATHDT': 0, 'BPCONTFCT_ORG': 0,
'LEGAL_ENTYT': 0, 'ZAMESTNANEC': 0, 'DLUZNIK': 0, 'BONITA_OP_Sum': 0, 'POCET_SMLUV_PLYN': 0,
'POCET_SMLUV_PLYN_AKTIVNI': 0, 'POCET_SMLUV_PLYN_VAKTIVACI': 0, 'POCET_SMLUV_EE': 0, 'POCET_SMLUV_EE_AKTIVNI': 0,
'POCET_SMLUV_EE_VAKTIVACI': 0, 'EINZDAT': 0, 'AUSZDAT': 0, 'DIVISIONT': 0, 'C_ABSZYKT': 0, 'UCACTDETIDT': 0,
'UCCON_CLAST': 0, 'DISTRIBUTOTT': 0, 'SPOTREBA_MWH_AKTUALNI_PLYN': 0, 'SPOTREBA_MWH_AKTUALNI_EE': 0,
'ZZEDIRATE': 0, 'ZZVBSARTT': 0, 'MS_REGIONT': 0, 'MS_COMMU_CODE': 0, 'MS_krajn': 0, 'MS_okresn': 0,
'MS_POCET_OBYVATEL': 0, 'OP_REGIONT': 0, 'OP_COMMU_CODE': 0, 'KA_REGIONT': 0, 'KA_COMMU_CODE': 0,
'WU_branch': 0, 'WU_distance': 0, 'WU_duration': 0, 'id_p': 0, 'id'];
