\f fill;

\r aaa.txtx l = 0;

\pda n = ca, no = "all";

\q;

\pda n = ['GENDER_TXT', 'TITLE_ACA1T', 'VEK', 'ZZDEATHDT', 'BPCONTFCT_ORG',
'LEGAL_ENTYT', 'ZAMESTNANEC', 'DLUZNIK', 'BONITA_OP_Sum', 'POCET_SMLUV_PLYN',
'POCET_SMLUV_PLYN_AKTIVNI', 'POCET_SMLUV_PLYN_VAKTIVACI', 'POCET_SMLUV_EE', 'POCET_SMLUV_EE_AKTIVNI',
'POCET_SMLUV_EE_VAKTIVACI', 'EINZDAT', 'AUSZDAT', 'DIVISIONT', 'C_ABSZYKT', 'UCACTDETIDT',
'UCCON_CLAST', 'DISTRIBUTOTT', 'SPOTREBA_MWH_AKTUALNI_PLYN', 'SPOTREBA_MWH_AKTUALNI_EE',
'ZZEDIRATE', 'ZZVBSARTT', 'MS_REGIONT', 'MS_COMMU_CODE', 'MS_krajn', 'MS_okresn',
'MS_POCET_OBYVATEL', 'OP_REGIONT', 'OP_COMMU_CODE', 'KA_REGIONT', 'KA_COMMU_CODE',
'WU_branch', 'WU_distance', 'WU_duration', 'id_p', 'id'], no = "all";

\dp;
